Fix activities creation for free tickets
CommitChange/houdini pull request #16
Opened 2021-04-14 15:10 UTC by clarissalimab

Uses `left_outer_join` on `payments.id` so that free tickets - which don't
have `payment.id` - have their activities created.

The script to generate activities for the tickets with missing activities could be something like:
```ruby
ticket_ids = Ticket.includes(:activities).where('activities.id IS NULL').flat_map(&:id)
ticket_ids.each do |id|
  InsertActivities.for_tickets(id)
end
```

***
Resolves [tix #2838](https://github.com/CommitChange/tix/issues/2838).

2021-04-14 15:58 UTC, clarissalimab commented
I ran this script locally and the activities for the free tickets were created. I did a simple smoke test to see if it worked:

This supporter had no activities and had a free ticket (nonprofit: 4663, event: 2626, supporter: 3121365)
![image](https://user-images.githubusercontent.com/15739610/114740993-bc623880-9d20-11eb-95c7-216cba05154c.png)

After I ran the script, the activity was created:
![image](https://user-images.githubusercontent.com/15739610/114741351-0f3bf000-9d21-11eb-9c99-e3711e985d5e.png)

2021-04-14 16:15 UTC, wwahammy commented
Could you add a unit test to verify this works in `spec/lib/insert/insert_tickets_spec.rb`?

2021-04-14 16:19 UTC, wwahammy requested changes
When you're ready for me to review it again, just hit request review so I'm notified.

2021-04-19 20:53 UTC, wwahammy commented
@clarissalimab have you tested: 
```ruby
ticket_ids = Ticket.includes(:activities).where('activities.id IS NULL').flat_map(&:id)
InsertActivities.for_tickets(ticket_ids)
```
for fixing the old activities?

2021-04-20 15:18 UTC, clarissalimab commented
@wwahammy yes, I tested like I mentioned on [this comment](https://github.com/CommitChange/houdini/pull/16#issuecomment-819629836). After the test I ran `Ticket.includes(:activities).where('activities.id IS NULL')` and it returned nothing. Is there any other thing that you think I should look at?

2021-04-20 16:15 UTC, wwahammy commented
> Is there any other thing that you think I should look at?

Probably not honestly, I just wanted to make sure it had been tested :)

2021-04-20 16:15 UTC, merged

2021-04-20 16:30 UTC, wwahammy reviewed
We merged :+1