Temporary module to remove payment dupes
CommitChange/houdini pull request #222
Opened 2022-01-15 23:12 UTC by clarissalimab

Part of https://github.com/CommitChange/tix/issues/3553

2022-01-15 23:15 UTC, clarissalimab commented on lib/payment_dupes.rb
> +            raise 'done'
Once it gets approved I'm going to remove this line.

2022-01-16 01:40 UTC, wwahammy requested changes
We can't merge as is but I guess this is fine for just running the tests required of the CommitChange/tix#3553

2022-01-16 01:40 UTC, wwahammy commented on db/migrate/20220115171649_add_matched_to_payments.rb
> +    add_column :payments, :matched, :boolean, default: false
Please put the matched field on another model and use a has_one reference from Payment to the table and a belongs_to from the table to Payment. Adding fields to a model is not good practice and it breaks all of the tests

2022-02-11 05:20 UTC, wwahammy approved these changes
Seems good. Again, it's hard to tell. Nothing jumps out at me as wrong.

2022-02-11 07:42 UTC, merged