Consider nonprofit timezone when displaying dates
CommitChange/houdini pull request #27
Opened 2021-05-06 19:08 UTC by clarissalimab

2021-05-10 21:58 UTC, wwahammy commented on spec/lib/query/query_supporters_spec.rb
> +  let(:supporter1) { force_create(:supporter, nonprofit: np, name: 'Cacau')}
:smile: :dog:

2021-05-11 19:05 UTC, clarissalimab commented on spec/lib/query/query_supporters_spec.rb
> +  let(:supporter1) { force_create(:supporter, nonprofit: np, name: 'Cacau')}
it was necessary :laughing:

2021-05-12 16:21 UTC, wwahammy commented
This PR is only addressing payment timing issues with supporters, not the payments dashboard, right?

2021-05-12 17:08 UTC, wwahammy requested changes
Searchwise, this does fix the referenced issue. However, it doesn't address the issue of the last payment listed on the dashboard being always in UTC. That should be addressed as well to close this issue.

If you feel it can be done this sprint, we can move it into here. Otherwise, we can split it out. What do you think @clarissalimab?

Example of the problem:
![Screenshot from 2021-05-12 12-00-38](https://user-images.githubusercontent.com/94169/118015680-2a971c80-b31a-11eb-9fed-91141d6c8bdc.png)


But look at the time for the recurring donation on 3/31 at: 
![Screenshot from 2021-05-12 12-00-27](https://user-images.githubusercontent.com/94169/118015717-34b91b00-b31a-11eb-90fe-1d8bf9cc5478.png)

2021-05-13 15:05 UTC, clarissalimab commented
@wwahammy I'll take a look!

2021-05-14 15:45 UTC, clarissalimab commented
@wwahammy, it's working now with the fix we did yesterday!

This is how it looks on the supporters list:
![image](https://user-images.githubusercontent.com/15739610/118295087-d7f06880-b4b1-11eb-9d61-8e5b5c5038b6.png)

This is how the details look like (I've updated my local database, that's why there are more registers there):
![image](https://user-images.githubusercontent.com/15739610/118295353-1ede5e00-b4b2-11eb-8108-6229591f983d.png)

2021-05-14 16:06 UTC, wwahammy approved these changes
I think this all looks good. Let's ship it!

2021-05-14 16:07 UTC, merged

2021-05-14 16:09 UTC, wwahammy commented
So, I just thought of something: are dates on exports being properly exported in the nonprofit's timezone? We should check that although I think that might be a separate issue.

2021-05-14 16:57 UTC, clarissalimab commented
@wwahammy I'll check that, if not, I'll create an issue, okay?