In subtransaction_payment jbuilder, get `created` from the paymentable, not subtransaction_payment
CommitChange/houdini pull request #672
Opened 2023-05-11 22:09 UTC by awadyas

**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

Closes https://github.com/CommitChange/tix/issues/4040

2023-05-12 16:28 UTC, wwahammy requested changes
Hmmm, this does fix the problem in a sense but it's not quite the right layer.

We'll need to be able to search and sort SubtransactionPayments by their `created` value. That means, for this PR, `SubtransactionPayment#created` to be set or updated when the `legacy_payment.date` is set or changed.

2023-05-12 18:49 UTC, awadyas commented
> We'll need to be able to search and sort SubtransactionPayments by their created value. That means, for this PR, SubtransactionPayment#created to be set or updated when the legacy_payment.date is set or changed.

How does this sound as an approach: Adding a method on `Payment` to sync the `date` from the legacy payment to `SubtransactionPayment#created`, and putting the sync method in `create` and `update` in `PaymentsController`, conditionally, only if the payment has an associated subtransaction payment?

2023-05-12 18:52 UTC, awadyas commented
So something like this

(in payments_controller.rb)
```
def create
  ...
  @payment.sync_date_to_subtransaction_payment if @payment.subtransaction_payment
end

def update
  ...
  @payment.sync_date_to_subtransaction_payment if @payment.subtransaction_payment
end

def sync_date_to_subtransaction_payment
  subtransaction_payment.created = date
end
```

2023-05-12 19:06 UTC, wwahammy commented
Unfortunately, there are ways in which payments can be updated and created that are not through an http request. For example, a recurring donation could run and a payment would be created for that day but no http request would have occurred.

This will have to happen in InsertDonation, UpdateDonation, UpdateTickets, etc.

2023-05-13 00:39 UTC, wwahammy reviewed
Looks good. Is it possible to unit test the changes in InsertTickets too?

2023-05-15 15:02 UTC, awadyas commented
> Is it possible to unit test the changes in InsertTickets too?

Yes, forgot about that lol :joy: I"m on it

2023-05-15 23:42 UTC, wwahammy requested changes
One quick tweak I think

2023-05-15 23:42 UTC, wwahammy commented on spec/lib/insert/insert_tickets_spec.rb
> +            expect(subtransaction_payment.created).to eq(legacy_payment.created_at)
This should be the `legacy_payment.date`. On offsite payments, date will not be the same as the `created_at` time.

```suggestion
            expect(subtransaction_payment.created).to eq(legacy_payment.date)
```

2023-05-16 17:47 UTC, wwahammy approved these changes

2023-05-16 17:58 UTC, merged