Fix/readme updates
CommitChange/houdini pull request #695
Opened 2023-06-26 20:50 UTC by camckin10

The one-time Mac setup instructions for CC needed to be updated.

This PR contains the following changes:

Ruby Version changes

Removing version number '2.6' from 'rbnenv install' and 'rbenv local' commands
Adding the command to switch ruby versions locally 'rbenv shell (version #)
Node Version changes

Reordering the steps required to install nvm on Mac
Adding command 'brew info nvm' for user to see which remaining steps are needed in setup process
Postgresql Changes

Adding postgresql commands to start and stop services: 'brew services start postgresql@[version #]' and 'brew services stop postgresql@[version #]'

**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

2023-06-26 21:17 UTC, wwahammy requested changes
Welcome to CommitChange and Houdini @camckin10! I'm excited to have you involved. 

Really good start. I have a few tweaks I'd like you to make. Once those are done, it'll be ready to merge.

2023-06-26 21:17 UTC, wwahammy commented on README.md
> +Add the following lines to your ~/.bashprofile or ~/.zshrc:
Commenting the line makes it possible for someone to copy and paste the script  as a whole.

```suggestion
# Add the following lines to your ~/.bashprofile or ~/.zshrc:
```

2023-06-26 21:17 UTC, wwahammy commented on README.md
> +Reference Stack Overflow post: https://stackoverflow.com/questions/53118850/brew-install-nvm-nvm-command-not-found
Same comment as before

```suggestion
# Reference Stack Overflow post: https://stackoverflow.com/questions/53118850/brew-install-nvm-nvm-command-not-found
```

2023-06-26 21:17 UTC, wwahammy commented on README.md
> +brew services start postgresql@ [insert version number]
Two things:

1. Please put the actual version number here. 
2. Is this required normally in order to get started? Or is it simply helpful info? If it's helpful info, it can be removed. The key is someone should be able to copy and paste and run the script into their terminal.

2023-06-26 21:17 UTC, wwahammy commented on README.md
> +brew services stop postgresql@ [insert version number]
Same comment as above.

2023-06-26 21:19 UTC, camckin10 commented on README.md
> +brew services start postgresql@ [insert version number]
Yes its normally required to get postgres started.

2023-06-27 01:29 UTC, wwahammy requested changes
Thanks @camckin10. Just a few more tweaks. Let me know if you have any questions.

2023-06-27 01:29 UTC, wwahammy commented on README.md
> +* Ruby
Please undo this change. Ruby 2.6 is the minor version of Ruby that is compatible.

2023-06-27 01:29 UTC, wwahammy commented on README.md
> +The frontend is written in a few custom frameworks, the largest of which is called Flimflam.
Please revert this formatting change

2023-06-27 01:29 UTC, wwahammy commented on README.md
> +#### Get the code
Please revert this formatting change

2023-06-27 01:29 UTC, wwahammy commented on README.md
> +brew services stop postgresql@12
I don't think I understand why this line is here. If they do this, they won't be able to use the software, right?

2023-06-27 01:29 UTC, wwahammy commented on README.md
> +- All new front end code should be written in Typescript
Please remove this formatting change.

2023-06-27 14:24 UTC, camckin10 commented on README.md
> +brew services stop postgresql@12
@wwahammy  This more so for the dev to know the command *when* they want to stop postgres.

2023-06-27 14:57 UTC, wwahammy commented on README.md
> +brew services stop postgresql@12
Ah. Well we don't want it here because then users can't copy and paste the entire script as-is.

2023-06-29 14:47 UTC, wwahammy approved these changes
There are a few formatting changes that would be good to avoid in the future but let's merge :slightly_smiling_face:

2023-06-29 14:47 UTC, merged