Feature/jbuilder view for nonprofit sub
CommitChange/houdini pull request #706
Opened 2023-07-13 20:36 UTC by camckin10

The jbuilder file should be at app/views/mailchimp/nonprofit_user_subscribe.json.jbuilder. It will have two class variables available:

@nonprofit: the Nonprofit of the nonprofit user to be added
@user: the User to be added
The output should include the following fields:

status: 'subscribed'
email_address: @user.email
merge_fields: an object with the following fields:
NONPROFIT_ID: @nonprofit.id

Closes [Github ticket](https://github.com/CommitChange/tix/issues/4106)
**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

2023-07-13 20:36 UTC, camckin10 commented
@wwahammy  Looking forward to feedback on the ticket..especially the spec file. Thank you!

2023-07-14 21:48 UTC, wwahammy requested changes

2023-07-14 21:48 UTC, wwahammy commented on spec/views/mailchimp/nonprofit_user_subscribe.json.jbuilder_spec.rb
> +      # view.lookup_context.prefixes = view.lookup_context.prefixes.drop(1)
I discovered it was needed at one point. I never was sure why. Make sure it's there.

As for where they're defined, it's super deep in Rails.

2023-07-14 21:48 UTC, wwahammy commented on spec/views/mailchimp/nonprofit_user_subscribe.json.jbuilder_spec.rb
> +      assign(:user, create(:user, NONPROFIT_ID: '123456'))
Users have roles. One of those roles, could be associated with a nonprofit. In that case, you'd need to use that. I think it'd help if we talked through how you came up with this particular attribute.

2023-07-14 21:48 UTC, wwahammy commented on spec/views/mailchimp/nonprofit_user_subscribe.json.jbuilder_spec.rb
> +  describe 'not adding new subscriber to nonprofit list', skip: 'TODO' do
Generally, you shouldn't write parts of a spec that you skip. We actually should go back and document that we should fix the spec in `list.json.jbuilder.spec`.

2023-07-14 21:48 UTC, wwahammy commented
Good start @camckin10!

2023-07-18 21:01 UTC, wwahammy requested changes
One tweak @camckin10 and then it's ready to go. Nice work!

2023-07-18 21:01 UTC, wwahammy commented on spec/views/mailchimp/nonprofit_user_subscribe.json.jbuilder_spec.rb
> +  describe 'not adding new subscriber to nonprofit list', skip: 'TODO' do
This describe section shouldn't be needed. We're not testing what is rendered when not adding a subscriber to the list because nothing gets rendered.

2023-07-19 17:48 UTC, wwahammy approved these changes
:+1:

2023-07-19 17:48 UTC, merged