Create a sync_nonprofit_users method
CommitChange/houdini pull request #724
Opened 2023-07-31 19:59 UTC by camckin10

At first, and occasionally in the future, we'll want to bulk sync the nonprofit users on the Mailchimp NP list.

Create a "sync_nonprofit_users" method in Mailchimp that queues a ActiveJobs to add each member to the NP list.
Add a spec to show that it works

Closes tix [#4130](https://github.com/CommitChange/tix/issues/4130)

**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

2023-08-09 16:44 UTC, wwahammy requested changes
Thanks @camckin10! There are a few changes required here.

2023-08-09 16:44 UTC, wwahammy commented on spec/lib/mailchimp_spec.rb
> +			expect Mailchimp.sync_nonprofit_users(DripEmailList.first)
I'm not sure I understand what is being checked here.

2023-08-09 16:44 UTC, wwahammy commented on app/legacy_lib/mailchimp.rb
> +      MailchimpNonprofitUserAddJob(np_user).perform_now
This run all of these jobs on the current thread. What we're looking for is to run them all on background threads. We need to queue them up using `#perform_later`

2023-08-11 16:06 UTC, wwahammy commented on spec/lib/mailchimp_spec.rb
> -
We do need to test this, we didn't have an opportunity to go through the testing however. During our pairing session. I can do work on that today, I think.

2023-08-12 18:40 UTC, wwahammy commented
@camckin10 I added back  in the commented out spec and used the [matching arguments](https://rspec.info/features/3-12/rspec-mocks/setting-constraints/matching-arguments/) feature from rspec. Please review the changes let me know if this works for you.

2023-08-14 14:49 UTC, camckin10 commented
@wwahammy  Looks great! I cannot approve my own PR...So its good to go for me!

2023-08-14 15:06 UTC, wwahammy approved these changes

2023-08-14 15:06 UTC, merged