Dockerized developer environment
CommitChange/houdini pull request #951
Opened 2024-11-22 19:13 UTC by thena-seer-sfg

**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

Adds a working  first-draft  dockerization for the developer environment. I focused on getting  an MVP with parity working. There's probably a lot of room for clean up and optimization, and I welcome such feedback!

I also added some troubleshooting tips  for the bare metal Mac setup in the README based on some problems I ran into.

2024-11-22 20:03 UTC, wwahammy requested changes
Thanks @thena-seer-sfg for this! Overall, I think this makes sense. Most of my comments are minor and there's only one that actually requires changes.

There are some tweaks that would be good and there are some use-cases we need that won't quite work as-is. I'll list those in Tix but I don't think we need to block on that.

Outside of the one change I'm requesting, I'd like other members of the @CommitChange/devs to comment on it and see if makes sense to them.

2024-11-22 20:03 UTC, wwahammy commented on README.md
> +brew services start postgresql@16
Generally, I'd prefer this as a separate PR as it's not really related to the dockerizing. But it's not a huge issue either way.

2024-11-22 20:03 UTC, wwahammy commented on config/database.yml
> +  host: <%= ENV['DATABASE_HOST']  || 'localhost' %> # This breaks mac? Is it needed? Yes, by docker
How does it break on mac?

2024-11-22 20:03 UTC, wwahammy commented on config/database.yml
> +#   gem install pg -- --with-pg-config="${HOMEBREW_PREFIX}/opt/libpq/bin/pg_config"
Again, it'd be nice if this was in a separate PR but it's not the end of the world.

2024-11-22 20:03 UTC, wwahammy commented on docker-compose.yml
> +      - ~/tmp/houdini/db:/var/lib/postgresql/data
Is there any reason we couldn't put this in a child directory of the project root instead of `~/tmp/houdini/db`? If we hard code it here, that means there can only ever be one instance of this dev environment setup at a time. Not end of the world but not ideal.

2024-11-22 20:17 UTC, thena-seer-sfg commented on config/database.yml
> +  host: <%= ENV['DATABASE_HOST']  || 'localhost' %> # This breaks mac? Is it needed? Yes, by docker
Deleting this line fixed the segmentation fault we were seeing, for whatever reason. I didn't really ever find a reason why, just a tip that removing this fixed it for others and it did for me too.

2024-11-22 20:20 UTC, wwahammy commented on config/database.yml
> +  host: <%= ENV['DATABASE_HOST']  || 'localhost' %> # This breaks mac? Is it needed? Yes, by docker
Wild

2024-11-22 20:30 UTC, thena-seer-sfg commented on config/database.yml
> +  host: <%= ENV['DATABASE_HOST']  || 'localhost' %> # This breaks mac? Is it needed? Yes, by docker
I found an alternate solution via an env variable, and have updated this and the readme accordingly.

2024-11-22 20:31 UTC, thena-seer-sfg commented on docker-compose.yml
> +      - ~/tmp/houdini/db:/var/lib/postgresql/data
oh yeah this was copied from public repo, will update

2024-11-22 20:33 UTC, thena-seer-sfg commented on README.md
> +brew services start postgresql@16
I agree, and it has been such a process getting here and things are so tangled that I'm inclined to let it slide this time.

2024-11-22 20:33 UTC, thena-seer-sfg commented on config/database.yml
> +#   gem install pg -- --with-pg-config="${HOMEBREW_PREFIX}/opt/libpq/bin/pg_config"
See other comment. Agreed but inclined to let it slide.

2024-11-22 20:35 UTC, wwahammy approved these changes

2024-11-24 18:43 UTC, wwahammy commented
No one commented on this so I'm going to merge.

2024-11-24 18:43 UTC, merged