remove ramda from nonprofits (incomplete)
CommitChange/houdini pull request #973
Opened 2024-12-19 17:32 UTC by hejkal

incomplete (some ramda left here still)
split out from https://github.com/CommitChange/houdini/pull/964

2025-01-31 20:28 UTC, wwahammy requested changes
Nice work @hejkal! Just a few tweaks that should be done and then we can test on staging once merged.

2025-01-31 20:28 UTC, wwahammy commented on client/js/nonprofits/donate/components/info-step/customFields/legacy.ts
This is a legacy version the customFields function. This is one of those examples I mentioned where I moved some code into a two files and tried to implement it both with and without ramda. If you're confident that legacy.ts and new.ts are doing the same thing, you should change the import in client/js/nonprofits/donate/parseFields/customField/index.ts to point at new.ts instead

2025-01-31 20:28 UTC, wwahammy commented on client/js/nonprofits/supporters/index/sidepanel/generate-content.js
> + // , body: canView ? [...body, ...thread] : [...body, ...signIn]
Let's just remove this commented line.

2025-01-31 20:28 UTC, wwahammy commented on client/js/nonprofits/donate/get-params.js
> +  const outputParams = evolve(merge(params))
This SEEMS right but this is some crucial code on the website. If this is broken, payments stop working as well as the widget. We'll need to focus on testing this on staging.

2025-02-03 18:46 UTC, hejkal commented on client/js/nonprofits/donate/components/info-step/customFields/legacy.ts
legacy.ts and new.ts are identical, I'll go ahead and do that

2025-02-03 18:50 UTC, hejkal commented on client/js/nonprofits/donate/get-params.js
> +  const outputParams = evolve(merge(params))
makes sense, for sure. I'm pretty certain it's correct, and the widget worked fine in local testing

2025-02-04 18:40 UTC, wwahammy approved these changes
Looks good to me!

2025-02-04 19:04 UTC, merged